### ISSUE TITLE
Case-insensitive AMD search, notification of no module found

### ISSUE THREAD

**Issue by tydevries** [cefolger/needsmoredojo#115]
Enhancement request: when adding a module (Ctrl + Shift + O, 2), the search is case-sensitive. I am lazy and do not want to bother camel-casing the imports, so a case-insensitive search would be bodacious.

EDIT: Could a notification be surfaced to the user when no such module is found? For example, when I search for module "foo" (let's say /baz/bar/Foo is the actual package directory), nothing is found, so NMD automatically adds "foo" to my list of AMD declarations and corresponding function callback. This would be nice if there were only one valid search result, but since there are none, I have to undo the import and search again.

**Comment by cefolger** [comment]
I will explore this for 0.5.1, hopefully there is a way to do a case-insensitive search using the FilenameIndex.

**Comment by cefolger** [comment]
Well on further investigation I will have to push this back to the next one. Sorry!
