### ISSUE TITLE
Full support of attach points

### ISSUE THREAD

**Issue by akhokhlov** [cefolger/needsmoredojo#147]
In section "Navigate to Attach Point" (https://github.com/cefolger/needsmoredojo#navigate-to-attach-point) you say that " However, note that the attach point references are flagged as unresolved variables even though they can be looked up.".

But it would be really helpful to flag them as resolved and event better enable auto-completion if possible.

Thank you.

**Comment by cefolger** [comment]
You're right, I don't like them being flagged as unresolved. I will take another look at this as I've learned more since adding that feature.

**Comment by cefolger** [comment]
Unfortunately I'll have to defer this, as I've looked and it doesn't seem IntelliJ provides a way to supply references to properties in JavaScript, unless they are string literals. 

(Using a JavaScriptReferenceContributor only results in JSLiteralExpressions being able to have references attached, not sure why.)

**Comment by cefolger** [comment]
Ok, I spoke too soon. I was able to implement this by overriding the inspection that flags unresolved variables.
