### ISSUE TITLE
NPE when attempting to goto standard, non-attachpoint declaration

### ISSUE THREAD

**Issue by belefuu** [cefolger/needsmoredojo#148]
Experienced this with 5.2 and now with 6.0, having just updated. After enabling Needs More Dojo, attempting to goto declaration (via ctrl + click or ctrl + b on a variable) throws a NPE. This is happening for standard local variables, I'm not even attempting to get the attachpoint business to work.

Here's the relevant portion of the stacktrace:

```
NullPointerException
    at com.chrisfolger.needsmoredojo.core.amd.objectmodel.TemplatedWidgetUtil.findTemplateFromDeclare(TemplatedWidgetUtil.java:80)
    at com.chrisfolger.needsmoredojo.core.amd.objectmodel.TemplatedWidgetUtil.findTemplatePath(TemplatedWidgetUtil.java:41)
    at com.chrisfolger.needsmoredojo.intellij.reference.AttachPointGotoDeclarationHandler.getGotoDeclarationTargets(AttachPointGotoDeclarationHandler.java:37)
    at com.intellij.codeInsight.navigation.actions.GotoDeclarationAction.findTargetElementsNoVS(GotoDeclarationAction.java:208)
```

All I can guess from the stacktrace and looking at the corresponding code is that it is treating every variable as a potential attachpoint, and then hitting the NPE when attempting to process non-attachpoints.

**Comment by cefolger** [comment]
belefuu, 

Does this occur in a module that uses _TemplatedWidget? If so, can you give me an example of a templateString definition that fails? 

I really thought I had fixed the problems with attach point jumping in 0.5.2. Sorry about that.

**Comment by belefuu** [comment]
Aha. Ok, I think this is on my end. My apologies, still getting used to the plugin.

I can confirm that this is only happening in cases where the templateString is defined with a hardcoded path that depends on the code running from a specific location on the web server. Thought I'd replaced all of those with proper Dojo package references, but it looks like in this instance the hardcoded path was still being used.

So, from my standpoint, the issue is closed, I just need to remain vigilant and refactor any of those hardcoded templateString paths I come across. I'm fine with the issue being closed, unless the NPE still seems like an issue to you given those parameters.

**Comment by cefolger** [comment]
Ok, thanks for clarifying and narrowing the issue down. It needs to be fixed ("Internal IDE error" doesn't look too good for the plugin) but I will remove the high priority label I added. Thanks for bringing this issue to my attention.
