### ISSUE TITLE
Support for name-clash resolution

### ISSUE THREAD

**Issue by scbird** [cefolger/needsmoredojo#153]
In our project, we have several util modules in different directories, and often have to import more than one of these into the same module, which we do as so:

define(["./data/util", "./ui/util"], function(dataUtil, uiUtil){ ...

While we can tell Needs More Dojo about these though the configuration screen, it would be even better if it could recognise this pattern automatically.

Bonus points if it can also recognise relative paths:

eg in foo/bar/data.js:
define(["../myModule", "./myModule"], function(fooMyModule, barMyModule){ ...

**Comment by cefolger** [comment]
Needs More Dojo will now detect the situation you described, and will try to match "myModule" with "fooMyModule" based on its path. It will resolve the relative path as well so should detect both cases you describe. 

In addition, the add new import action will check if a new import would result in a duplicate parameter and if so, prefix the name with the directory. 

Closing for now, thanks for reporting this!
