### ISSUE TITLE
Resolve relative module paths

### ISSUE THREAD

**Issue by scbird** [cefolger/needsmoredojo#155]
When adding module naming convention exceptions, both relative and absolute references must be added. It would be great if the code inspector resolved relative references so that naming exceptions worked regardless of how the module is referenced. 

_Configuration settings:_
Add module naming convention exception  /foo/bar/blah = myModule

_Current behaviour:_
define(["/foo/bar/blah"], function(myModule){ ...
is marked as valid
define(["./blah"], function(myModule){ ... (in module /foo/bar/anotherModule)
is marked as invalid

_Desired behaviour:_
define(["./blah"], function(myModule){ ... (in module /foo/bar/anotherModule)
is also marked as valid

**Comment by cefolger** [comment]
After resolving #153, this was easily resolved as well.
