### ISSUE TITLE
setup issues

### ISSUE THREAD

**Issue by stemey** [cefolger/needsmoredojo#158]
I have a standard dojo directory layout. My project is in folder app and dojo, dijit and so are siblings. I setup dojo sources as the common parent folder. It works. Although I had to add all those modules as content roots, which might not be documented really well in "needsmoredojo".

Im am now using bower and want to have my dojo libs inside my webstorm project. So I have a directory app and below I have the directories dojo, dijit and src. Src contains my project's javascript sources. Once again all libs have a common parent folder, which I setup as dojo and project sources folder - and as content root. Adding Imports and Navigating to sources via module exports does not work. The files are correctly identified in the require (e.g. define(['/dojo/request/xhr'] is clickable) statement though.

Thanks

**Comment by cefolger** [comment]
Hi Stefan, 

I'm not sure I understand your project layout -- but I used bower to download dojo and setup a test project. Could you tell me if/how your project layout differs from the one I setup below? Sorry for the delay. 

![image](https://f.cloud.github.com/assets/2001681/2029500/e5b0e742-88e5-11e3-8f2e-8acaee46876c.png)
![image](https://f.cloud.github.com/assets/2001681/2029502/f7418e4e-88e5-11e3-9e81-81da2da0415f.png)

**Comment by stemey** [comment]
Somehow it has resolved itself. It is working really well and it is a really great tool, that I don't want to miss.
Does it actually work with requirejs as well?
