### ISSUE TITLE
Add option to choose single or double quote usage for module IDs

### ISSUE THREAD

**Issue by jcfranco** [cefolger/needsmoredojo#164]
MIDs added by "Add new AMD import" use single quotes. It'd be nice to be able to choose between single or double quotes in the settings.

**Comment by dasa** [comment]
:+1:

**Comment by jcfranco** [comment]
This seems to be addressed in https://github.com/cefolger/needsmoredojo/pull/157.

**Comment by cefolger** [comment]
Thanks jcfranco, this will be available in the 0.7 release.
