### ISSUE TITLE
Export/Import settings

### ISSUE THREAD

**Issue by dancrumb** [cefolger/needsmoredojo#167]
Is there a way to export and import NeedsMoreDojo settings, preferably via a config file in a repository.

It would be handy to be able to disseminate these across our team, so that they can run code inspections and get consistent results

**Comment by cefolger** [comment]
Hi Dan, 

All of the settings are stored in an xml file under the .idea folder of your project. The file is called needsmoredojoconfig.xml, and if you overwrite or change it then you should see the settings applied. Let me know if that works for you. 

Chris Folger
