### ISSUE TITLE
Support for generic AMD loader plugins

### ISSUE THREAD

**Issue by wskidmore** [cefolger/needsmoredojo#87]
Currently using custom [loader plugins](https://github.com/amdjs/amdjs-api/wiki/Loader-Plugins), which are supported with at least dojo's 1.8 loader raises as a name mismatch error.

Example:

``` js
define([
   'dojo/_base/declare', 
   'foo!bar'
], function(declare, bar) { 
    /* */ 
});
```

Both `foo!bar` and `bar` will be highlighted as "Mismatch between define foo!bar and parameter bar".

I think the confusion stems from the fact that the dojo plugins use the resource id half of the loader plugin string as a path to load a resource whereas the spec merely [states](https://github.com/amdjs/amdjs-api/wiki/Loader-Plugins#terms-) that the plugin will know how to handle (so not necessarily a relative path, could be anything).

**Comment by cefolger** [comment]
Thanks for pointing that out. I've only used the text and i18n plugins so haven't encountered this issue. Shouldn't be difficult to take this into account though.
