### ISSUE TITLE
Better support for WebJars

### ISSUE THREAD

**Issue by jeffmay** [cefolger/needsmoredojo#91]
I tried using this plugin with the Dojo webjar from http://www.webjars.org/

I wasn't able to find where the dojo source was from the IDE. I think because it is in a .jar file in the ~/.ivy2 cache. Anyway, I couldn't figure out how this worked together with web jars, so maybe there could be instructions on how to do this, if it is possible.

**Comment by cefolger** [comment]
Hi Jeff, 

I will look into this for the next version. I don't think it will work currently with the dojo sources in a jar (I did not test that use case). Thanks for bringing it up. 

Chris Folger

**Comment by cefolger** [comment]
(I will add the below text to the doc for 0.5) 

To use a jar or zip file as a location for dojo sources: 
- Add the zip or jar file as a content root. Do this by going to File/Project Structure/Modules/module name in IntelliJ IDEA or File/Settings/Directories in WebStorm. 
- Open the Needs More Dojo Settings under File/Settings/Needs More Dojo
- Set the dojo sources directory by using the browse button. Navigate to the root of the dojo/dijit/etc. packages. In the  web jar from webjars.org, that path is: jar file/META-INF/resources/webjars/dojo/1.9.1. Alternatively, use the auto-detect feature to pick this up. 
- Click "Apply" to save the changes.
