### ISSUE TITLE
Module naming conventions exceptions are not taken into consideration in the code inspection module

### ISSUE THREAD

**Issue by tommahieu** [cefolger/needsmoredojo#99]
It is possible to add an exception like this:

module name: "dojo/_base/lang", parameter name: "dLang".

When importing the 'lang' module using NeedsMoreDojo, the parameter is effectively called dLang, but is styled in red because the "check for inconsistently named imports" flags the import entry as inconsistent.  

It would be nice if the inspection took the module naming convention exceptions into account

**Comment by cefolger** [comment]
Tom, 

Looks like you found a bug as this should be current behavior. Sorry about that. I will fix this in the release I'm planning on to finish next week. 

Chris Folger

**Comment by tommahieu** [comment]
Ah, didn't know that.  Just started using the plugin:  great functionality btw (love the import and organize actions!)
